# Generated by Django 4.2.1 on 2023-06-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20230604_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressbook',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('Diproses', 'In Process'), ('Dikirim', 'Shipped'), ('Diterima', 'Delivered')], default='Diproses', max_length=150),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='mobile',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
