# Generated by Django 4.2.1 on 2023-06-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_useraddressbook_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddressbook',
            old_name='user_name',
            new_name='name_user',
        ),
    ]
