# Generated by Django 4.2.1 on 2023-06-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_user_name_useraddressbook_name_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddressbook',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
