# Generated by Django 4.2.1 on 2023-06-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_useraddressbook_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': '4. Sizes',
            },
        ),
    ]
