# Generated by Django 4.2.1 on 2023-06-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('NEW', 'New'), ('BEST', 'BEST'), ('SALE', 'SALE')], default='NEW', max_length=150),
        ),
    ]
