# Generated by Django 4.2.1 on 2023-06-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_product_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
