# Generated by Django 4.2.1 on 2023-06-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_productattribute_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
