# Generated by Django 4.2.1 on 2023-06-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_productattribute_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
